# Generated by Django 5.0.7 on 2024-07-29 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Charity', '0002_benefactor'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_limit_from', models.IntegerField(null=True)),
                ('age_limit_to', models.IntegerField(null=True)),
                ('date', models.DateField()),
                ('description', models.TextField(null=True)),
                ('gender_limit', models.CharField(choices=[('f', 'famale'), ('m', 'male')], max_length=1, null=True)),
                ('state', models.CharField(choices=[('P', 'pending'), ('W', 'waited'), ('A', 'assigend'), ('D', 'done')], default='P', max_length=1)),
                ('title', models.CharField(max_length=60)),
                ('assigned_benefactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Charity.benefactor')),
                ('charity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Charity.charity')),
            ],
        ),
    ]
